[build]
builder = "nixpacks"

[build.nixpacks]
nixPkgs = ["nodejs_20"]

[deploy]
startCommand = "npx prisma migrate deploy; npx prisma generate; npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
